theme: jekyll-theme-cayman
email : "bio_rdm@ed.ac.uk"
wiki : "https://www.wiki.ed.ac.uk/display/RDMS"
description : "Open outputs of monitoring COVID in wastewater in Scotland"
github:
  is_project_page: false
  
